### ISSUE TITLE
Incorrect dependency package in .deb package for 0.1.0

### ISSUE THREAD

**Issue by PandaJim** [KRTirtho/flemozi#3]
The .deb package for the 0.1.0 has incorrect dependency "keybinder-3.0" make it not installable in Debian/Ubuntu.

I think the dependency package name should be either `gir1.2-keybinder-3.0` or `libkeybinder-3.0-0 `.

See the keybinder-3.0 package in launchpad : https://launchpad.net/ubuntu/+source/keybinder-3.0

**Comment by novalu** [comment]
I can confirm this issue on Ubuntu 22.10.

**Comment by KRTirtho** [comment]
This has been fixed long time ago
