### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Rainman69** [KRTirtho/flemozi#30]
When I click on an emoji, the program closes 
better to add try icon 

https://github.com/KRTirtho/flemozi/assets/96986338/a008f8de-b4bc-4ea8-8278-3728321aed76

**Comment by KRTirtho** [comment]
It's not crashing. It is meant to close (hide). There is a shortcut (Ctrl + Alt + period) to show the app again
If you don't want the app to close after copying, press Ctrl while selecting the emoji

> better to add try icon

There's an open issue for that https://github.com/KRTirtho/flemozi/issues/29

**Comment by Rainman69** [comment]
ok

**Comment by KRTirtho** [comment]
Closing this
